import React, { useCallback, useEffect, useRef, useState } from "react";
import { AlertTriangle, BookOpen, Bot, ChevronDown, ChevronRight, History, Plus, Send, ShieldCheck, ThumbsDown, ThumbsUp, User } from "lucide-react";
import { api } from "../api";
import { Badge, Markdown, Card, useToast } from "../components/ui";

const MAX = 2000;
const tone = { High: "green", Medium: "amber", Low: "red" };

function ConfidenceMeter({ value, label }) {
  if (value == null) return null;
  return <span className="conf" title={`AI confidence ${Math.round(value * 100)}%`}><span className="conf-bar"><i style={{ width: `${value * 100}%` }} className={tone[label]} /></span>{label} · {Math.round(value * 100)}%</span>;
}

function Details({ icon: Icon, title, children, open: o = false }) {
  const [open, setOpen] = useState(o);
  return <div className="details"><button className="details-toggle" onClick={() => setOpen(!open)} aria-expanded={open}>{open ? <ChevronDown size={14} /> : <ChevronRight size={14} />}<Icon size={14} />{title}</button>{open && <div className="details-body">{children}</div>}</div>;
}

function AssistantMessage({ m, isLast, onChip, onRate, rated }) {
  const x = m.meta || {};
  return (
    <div className="msg bot">
      <div className="avatar bot"><Bot size={16} /></div>
      <div className="bubble-col">
        <div className={`bubble ${x.kind === "refusal" ? "refusal" : ""}`}><Markdown text={m.content} /></div>
        <div className="meta-row">
          {x.intent && <Badge tone="blue">{x.intent}</Badge>}
          {x.generation?.mode === "llm" && <Badge tone="purple" title={`Generated by ${x.generation.model}; citations and facts re-validated against the sources`}>AI-generated · validated</Badge>}
          {x.generation?.mode === "extractive" && x.sources?.length > 0 && <Badge tone="gray" title="Quoted directly from the approved article">From approved text</Badge>}
          <ConfidenceMeter value={x.confidence} label={x.confidence_label} />
          {x.escalation?.required && <Badge tone="orange" title={(x.escalation.reasons || []).join("; ")}><ShieldCheck size={11} /> Human review{x.escalation.team ? ` · ${x.escalation.team}` : ""}</Badge>}
          {x.sentiment === "negative" && <Badge tone="red">Frustration detected</Badge>}
          {x.urgency === "high" && <Badge tone="orange">Urgent</Badge>}
          {x.safety?.flags?.filter((f) => f.id !== "secret_shared").map((f) => <Badge key={f.id} tone="red"><AlertTriangle size={11} /> {f.label}</Badge>)}
        </div>
        {x.sources?.length > 0 && (
          <Details icon={BookOpen} title={`Sources (${x.sources.length})`} open={isLast && x.sources.length <= 1}>
            {x.sources.map((s) => (
              <div className="source" key={s.article_id}>
                <div><b>{s.title}</b> {s.primary && <Badge tone="green">Cited</Badge>}</div>
                <span>{s.source_name} · {s.article_id} · effective {s.effective_date}{s.score != null ? ` · match ${Math.round(s.score * 100)}%` : ""}</span>
                <p>{s.snippet}…</p>
              </div>))}
          </Details>
        )}
        {x.trace?.length > 0 && <Details icon={ShieldCheck} title="Why did the assistant do this?"><ol className="trace">{x.trace.map((t, i) => <li key={i}>{t}</li>)}</ol></Details>}
        {m.id > 0 && (
          <div className="rate">
            <button className={rated === "up" ? "on" : ""} aria-label="Helpful" onClick={() => onRate(m.id, "up")}><ThumbsUp size={13} /></button>
            <button className={rated === "down" ? "on" : ""} aria-label="Not helpful" onClick={() => onRate(m.id, "down")}><ThumbsDown size={13} /></button>
          </div>
        )}
        {isLast && x.suggestions?.length > 0 && (
          <div className="chips">{x.suggestions.map((s, i) => <button key={i} className={`chip ${s.style}`} onClick={() => onChip(s)}>{s.label}</button>)}</div>
        )}
      </div>
    </div>
  );
}

function WorkflowCard({ wf, busy, onSubmitFields }) {
  const [vals, setVals] = useState({});
  useEffect(() => setVals({}), [wf?.progress?.done, wf?.request_type]);
  if (!wf) return null;
  const pct = Math.round((wf.progress.done / wf.progress.total) * 100);
  const missing = wf.fields.filter((f) => f.status !== "done");
  const submit = (e) => { e.preventDefault(); const f = Object.fromEntries(Object.entries(vals).filter(([, v]) => v.trim())); if (Object.keys(f).length) onSubmitFields(f); };
  return (
    <Card title={wf.request_type} sub={`Routes to ${wf.team} · a person reviews every request`} icon={ShieldCheck} className="wf-card">
      <div className="progress"><i style={{ width: `${pct}%` }} /></div>
      <small className="muted">{wf.progress.done} of {wf.progress.total} details complete</small>
      <ul className="wf-fields">{wf.fields.filter((f) => f.status === "done").map((f) => <li key={f.id}><span>{f.label}</span><b>{f.value}</b>{f.prefilled && <Badge tone="gray">auto</Badge>}</li>)}</ul>
      {wf.stage === "collecting" && missing.length > 0 && (
        <form onSubmit={submit} className="wf-form">
          <b className="form-title">Or fill in the form</b>
          {missing.map((f) => (
            <label key={f.id}>{f.label}{f.id === wf.asking && <Badge tone="blue">asking</Badge>}
              <input value={vals[f.id] || ""} maxLength={500} placeholder={f.placeholder || f.hint} list={f.options.length ? `o-${f.id}` : undefined}
                onChange={(e) => setVals({ ...vals, [f.id]: e.target.value })} />
              {f.options.length > 0 && <datalist id={`o-${f.id}`}>{f.options.map((o) => <option key={o} value={o} />)}</datalist>}
            </label>))}
          <button className="primary wide" disabled={busy || !Object.values(vals).some((v) => v.trim())}>Save details</button>
        </form>)}
    </Card>
  );
}

export default function Assistant({ user, navigate }) {
  const toast = useToast();
  const [cid, setCid] = useState(null);
  const [msgs, setMsgs] = useState([]);
  const [wf, setWf] = useState(null);
  const [input, setInput] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [history, setHistory] = useState([]);
  const [showHistory, setShowHistory] = useState(false);
  const [rated, setRated] = useState({});
  const endRef = useRef(null); const taRef = useRef(null); const lastSend = useRef(null);

  useEffect(() => { endRef.current?.scrollIntoView({ behavior: "smooth", block: "end" }); }, [msgs, busy]);
  useEffect(() => { taRef.current?.focus(); }, [busy]);
  useEffect(() => { const t = taRef.current; if (t) { t.style.height = "auto"; t.style.height = Math.min(t.scrollHeight, 140) + "px"; } }, [input]);

  const loadHistory = useCallback(() => api("/api/conversations").then((d) => setHistory(d.items)).catch(() => {}), []);
  useEffect(() => { loadHistory(); }, [loadHistory]);

  const send = useCallback(async ({ text = "", action, payload, fields, label }) => {
    if (busy) return;
    const shown = (label || text || "").trim();
    lastSend.current = { text, action, payload, fields, label };
    setError(""); setBusy(true);
    if (shown) setMsgs((m) => [...m, { id: -Date.now(), role: "user", content: shown, meta: {} }]);   // optimistic bubble
    try {
      const r = await api("/api/chat", { method: "POST", body: { conversation_id: cid, message: text, action, payload: { ...(payload || {}), label: shown }, fields } });
      setCid(r.conversation_id); setWf(r.workflow || null);
      const { reply, conversation_id, ...meta } = r;
      setMsgs((m) => [...m, { id: r.message_id, role: "assistant", content: reply, meta }]);
      loadHistory();
    } catch (e) {
      setError(e.message);
    } finally { setBusy(false); }
  }, [busy, cid, loadHistory]);

  const submitText = () => {
    const text = input.trim();
    if (!text || busy) return;
    setInput("");                       // clear immediately so the message never "sticks" in the box
    send({ text });
  };
  const onKeyDown = (e) => {
    if (e.key === "Enter" && !e.shiftKey && !e.nativeEvent.isComposing) { e.preventDefault(); submitText(); }
  };
  const onChip = (s) => {
    if (s.kind === "message") return send({ text: s.message, label: s.message });
    if (s.action === "navigate") return navigate(s.payload.page);
    return send({ action: s.action, payload: s.payload, label: s.payload?.label || s.label });
  };
  const rate = async (id, rating) => { setRated((r) => ({ ...r, [id]: rating })); try { await api("/api/chat/feedback", { method: "POST", body: { message_id: id, rating } }); toast("Thanks for the feedback", "success"); } catch (e) { toast(e.message, "error"); } };
  const newChat = () => { setCid(null); setMsgs([]); setWf(null); setError(""); setInput(""); };
  const openConv = async (id) => {
    try { const d = await api(`/api/conversations/${id}`); setCid(id); setWf(d.active_workflow);
      setMsgs(d.messages.map((m) => ({ id: m.id, role: m.role, content: m.content, meta: m.meta }))); setShowHistory(false); } catch (e) { toast(e.message, "error"); }
  };

  const lastBot = [...msgs].reverse().find((m) => m.role === "assistant");
  const first = user.name.split(" ")[0];

  return (
    <div className="assistant-page">
      <div className="chat-col">
        <div className="chat-head">
          <div><h2><Bot size={18} /> CareOps Assistant</h2><span>Grounded in approved knowledge · a person reviews every request</span></div>
          <div className="actions">
            <button className="secondary sm" onClick={() => setShowHistory(!showHistory)}><History size={14} /> History</button>
            <button className="secondary sm" onClick={newChat}><Plus size={14} /> New chat</button>
          </div>
        </div>
        {showHistory && (
          <div className="history">{history.length === 0 ? <span className="muted">No earlier conversations.</span> : history.map((h) => (
            <button key={h.id} onClick={() => openConv(h.id)} className={h.id === cid ? "active" : ""}><b>{h.title}</b><small>{new Date(h.updated_at).toLocaleString()}</small></button>))}</div>)}
        <div className="chat-body" role="log" aria-live="polite" aria-label="Conversation">
          {msgs.length === 0 && (
            <div className="welcome">
              <div className="welcome-icon"><Bot size={34} /></div>
              <h3>Hi {first}, how can I help?</h3>
              <p>Ask a question or describe what you need. I'll answer from approved procedures, ask for anything missing, and route sensitive items to the right team.</p>
              <div className="chips center">{["I need a replacement ID card because mine is damaged", "How do I request a laptop?", "I need to book a meeting room", "How do I reset my password?"].map((s) => <button key={s} className="chip" onClick={() => send({ text: s, label: s })}>{s}</button>)}</div>
            </div>)}
          {msgs.map((m) => m.role === "user" ? (
            <div className="msg user" key={m.id}><div className="bubble-col"><div className="bubble">{m.content}</div></div><div className="avatar user"><User size={16} /></div></div>
          ) : <AssistantMessage key={m.id} m={m} isLast={m === lastBot && !busy} onChip={onChip} onRate={rate} rated={rated[m.id]} />)}
          {busy && <div className="msg bot"><div className="avatar bot"><Bot size={16} /></div><div className="bubble typing" aria-label="Assistant is typing"><i /><i /><i /></div></div>}
          {error && <div className="error-note" role="alert"><AlertTriangle size={16} /><span>{error}</span><button className="link" onClick={() => lastSend.current && send(lastSend.current)}>Retry</button></div>}
          <div ref={endRef} />
        </div>
        <div className="composer">
          <textarea ref={taRef} value={input} rows={1} maxLength={MAX} disabled={busy} aria-label="Message"
            placeholder="Type a message and press Enter…  (Shift+Enter for a new line)"
            onChange={(e) => setInput(e.target.value)} onKeyDown={onKeyDown} />
          <button className="send" onClick={submitText} disabled={busy || !input.trim()} aria-label="Send message"><Send size={17} /></button>
        </div>
        <div className="composer-foot"><span><ShieldCheck size={12} /> Never share passwords or codes. I can't give medical advice or approve requests.</span><span>{input.length}/{MAX}</span></div>
      </div>
      <aside className="side-col">
        {wf ? <WorkflowCard wf={wf} busy={busy} onSubmitFields={(fields) => send({ action: "fields", fields, label: "Submitted details from the form" })} />
          : <Card title="How this works" icon={ShieldCheck}>
              <ol className="how"><li><b>You ask</b> in your own words.</li><li><b>I check safety</b> first: no medical advice, no confidential data.</li><li><b>I answer from approved sources</b> and show them.</li><li><b>I ask only for what's missing</b>, then you confirm.</li><li><b>A person decides.</b> I never approve anything.</li></ol>
            </Card>}
        {lastBot?.meta?.request && (
          <Card title="Latest submission" icon={ShieldCheck}><div className="kv"><span>Reference</span><b>{lastBot.meta.request.request_id}</b><span>Team</span><b>{lastBot.meta.request.assigned_team}</b><span>Priority</span><b>{lastBot.meta.request.priority}</b></div></Card>)}
      </aside>
    </div>
  );
}
